export const SHOW_AUTH_PANEL = 'SHOW_AUTH_PANEL';
export const SHOW_ANNOTATE_PANEL = 'SHOW_ANNOTATE_PANEL';

export const SET_TARGET = 'SET_TARGET';

export const SHOW_WIDGET = 'SHOW_WIDGET';
export const HIDE_WIDGET = 'HIDE_WIDGET';
